# version: '3.8'

# services:
#   frontend:
#     build:
#       context: ./frontend
#     networks:
#       - ${NETWORK_NAME}
#     environment:
#       - ENV_LABEL=${ENV_LABEL}
#     ports:
#       - "8080:80"

#   backend:
#     build:
#       context: ./backend
#     networks:
#       - ${NETWORK_NAME}
#     environment:
#       - ENV_LABEL=${ENV_LABEL}
#     ports:
#       - "5000:5000"

# networks:
#   dev_network:
#     driver: bridge
#   accept_network:
#     driver: bridge
#   prod_network:
#     driver: bridge










version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
    networks:
      - ${NETWORK_NAME}
    environment:
      - ENV_LABEL=${ENV_LABEL}
    ports:
      - "${FRONTEND_PORT}:80"

  backend:
    build:
      context: ./backend
    networks:
      - ${NETWORK_NAME}
    environment:
      - ENV_LABEL=${ENV_LABEL}
    ports:
      - "${BACKEND_PORT}:5000"

networks:
  dev_network:
    driver: bridge
  accept_network:
    driver: bridge
  prod_network:
    driver: bridge
