# Utiliser une image de base Nginx pour servir les fichiers statiques
FROM nginx:alpine

# Copier les fichiers de l'application front-end
COPY index.html /usr/share/nginx/html/index.html

# Exposer le port 80
EXPOSE 80